spring.application.name=dynamicRecommendation

spring.datasource.secondary.url=jdbc:postgresql://localhost:5432/recommendation
spring.datasource.secondary.username=postgres
spring.datasource.secondary.password=postgres
spring.datasource.secondary.driver-class-name=org.postgresql.Driver

spring.liquibase.change-log=classpath:liquibase/changelog-master.yaml
spring.liquibase.data-source=secondDataSource