package ru.rules.dynamicRecommendation.model;

import jakarta.persistence.*;
import lombok.Getter;
import ru.rules.dynamicRecommendation.enums.ProductType;
import ru.rules.dynamicRecommendation.enums.TransactionType;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Entity representing a financial transaction in the system.
 * Stores information about monetary movements (deposits, withdrawals)
 * associated with users and financial products.
 * Corresponds to the "transactions" table in the database.
 */
@Getter
@Entity
@Table(name = "transactions")
public class Transaction {

    /**
     * Unique identifier of the transaction.
     * Automatically generated by the database using identity strategy (auto‑increment).
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Identifier of the user who performed the transaction.
     * Links the transaction to a specific user in the system.
     * Corresponds to the "user_id" column in the database.
     */
    @Column(name = "user_id")
    private Long userId;

    /**
     * Type of the financial product associated with the transaction.
     * Determines the product category (e.g., DEBIT, CREDIT, INVEST, SAVING).
     * Stored as a string in the database ("product_type" column) using EnumType.STRING.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "product_type")
    private ProductType productType;

    /**
     * Type of the transaction (deposit or withdrawal).
     * Defines the direction of the monetary movement:
     * - DEPOSIT: funds added to the account (increases balance)
     * - WITHDRAW: funds removed from the account (decreases balance)
     * Stored as a string in the database ("transaction_type" column) using EnumType.STRING.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "transaction_type")
    private TransactionType transactionType;

    /**
     * Amount of the transaction in monetary units.
     * Stored with high precision to avoid rounding errors in financial calculations.
     * Precision: 19 digits total, scale: 2 digits after the decimal point
     * (e.g., 1000.50).
     */
    @Column(precision = 19, scale = 2)
    private BigDecimal amount;

    /**
     * Timestamp indicating when the transaction was created.
     * Records the exact date and time of the transaction occurrence.
     * Corresponds to the "created_at" column in the database.
     */
    @Column(name = "created_at")
    private LocalDateTime createdAt;

    // Constructors

    /**
     * Default constructor required by JPA.
     */
    public Transaction() {
    }

    /**
     * Constructor to create a new transaction with basic details.
     * Sets the creation timestamp to the current time.
     *
     * @param userId          identifier of the user performing the transaction
     * @param productType     type of the financial product involved
     * @param transactionType type of the transaction (DEPOSIT or WITHDRAW)
     * @param amount          monetary amount of the transaction
     * @throws IllegalArgumentException if amount is null or negative
     */
    public Transaction(Long userId, ProductType productType,
                       TransactionType transactionType, BigDecimal amount) {
        if (amount == null) {
            throw new IllegalArgumentException("Transaction amount cannot be null");
        }
        if (amount.compareTo(BigDecimal.ZERO) < 0) {
            throw new IllegalArgumentException("Transaction amount cannot be negative");
        }

        this.userId = userId;
        this.productType = productType;
        this.transactionType = transactionType;
        this.amount = amount;
        this.createdAt = LocalDateTime.now(); // Автоматически устанавливаем текущую дату
    }

    public void setId(Long id) {
        this.id = id;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public void setProductType(ProductType productType) {
        this.productType = productType;
    }

    public void setTransactionType(TransactionType transactionType) {
        this.transactionType = transactionType;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
}